# Generated by Django 3.2.3 on 2021-05-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210516_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Блок документации',
                'verbose_name_plural': 'Блоки документации',
            },
        ),
    ]
