# Generated by Django 3.2.3 on 2021-05-16 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_documentationblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationBlockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('documentation_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.documentationblock')),
            ],
            options={
                'verbose_name': 'Элемент блока документации',
                'verbose_name_plural': 'Элементы блока документации',
            },
        ),
    ]
