# Generated by Django 3.2.3 on 2021-05-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_documentationblockitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trialsphotos/')),
            ],
            options={
                'verbose_name': 'Фото испытаний',
                'verbose_name_plural': 'Фото испытаний',
            },
        ),
    ]
